customhost = "employeedb.cj8azo2794kw.eu-west-1.rds.amazonaws.com" 
customuser = "admin"
custompass = "Leeraj21"
customdb = "employeedb"
custombucket = "myrdsbucketproject"
customregion = "eu-west-1"